Saas.Office.Auto.Web/Areas/Admin/Controllers/HeaderController.cs
using Saas.Office.Auto.Web.App_Start.Webstack;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Saas.Office.Auto.Web.Areas.Admin.Controllers
{
    //模板页Header
    public class HeaderController : Controller
    {
        // GET: Admin/Header
        public ActionResult Index()
        {
            return View();
        }
        [UserAuthorizeAttribute(false)]
        public PartialViewResult SysHeader()
        {
            return PartialView();
        }
        [UserAuthorizeAttribute(false)]
        public ActionResult LogOut()
        {
            return RedirectToAction("Index", "Login", new { area = "AdminLogin" });
        }
    }
}

Saas.Office.Auto.Web/Areas/Admin/Controllers/MenuController.cs
using Saas.Office.Auto.IService;
using Saas.Office.Auto.Model;
using Saas.Office.Auto.Service.Infrastructure;
using Saas.Office.Auto.Web.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Saas.Office.Auto.Web.Areas.Admin.Controllers
{
    //模板页——Menu
    public class MenuController : BaseController
    {
        private readonly IAuthorizedService _authorizedService;
        public MenuController(IAuthorizedService authorizedService)
        {
            this._authorizedService = authorizedService;
        }
        // GET: Admin/Menu
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult SysMenu(RouteViewModel model, string selfid, string parentid)
        {
            UserProfileBO UserInfo = this.userProfileBO;
            model.sysUserId = UserInfo.CurrentUser.Id;
            List<RouteViewModel> headerMenus = UserInfo.CurrentAuthorities.routeViewModel;
            if (headerMenus != null && headerMenus.Count() > 0)
            {
                foreach (var item in headerMenus)
                {
                    RouteChildViewModel pvm = item.routeChildViewModel.Where(m => m.controllerId == parentid).FirstOrDefault();
                    if (pvm != null)
                    {
                        pvm.isSelected = true;
                        pvm.childViewModel.Where(m => m.controllerId == selfid).FirstOrDefault().isSelected=true;
                    }
                }

            }
            return PartialView(headerMenus);
        }
    }
}

Saas.Office.Auto.Web/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SAAS-OA管理平台</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @*自定义样式始*@
    @Styles.Render("~/Content/css/global")
    @Styles.Render("~/Content/css/global/style")
    @Styles.Render("~/Content/css/global/layout")
    @Styles.Render("~/Content/css/plugins/datatables")
    @*自定义样式末*@
</head>
<body class="page-header-fixed page-sidebar-closed-hide-logo page-container-bg-solid">
    @*模板页页头部分始*@
    <div class="page-header navbar navbar-fixed-top">
        @{Html.RenderAction("SysHeader", "Header"); }
    </div>
    @*模板页页头部分末*@
    <div class="clearfix"> </div>
    @*模板页内容部分始*@
    <div class="page-container">
        @*模板页菜单部分始*@
        <div class="page-sidebar-wrapper">
            @{Html.RenderAction("SysMenu", "Menu"); }
        </div>
        @*模板页菜单部分末*@
        <div class="page-content-wrapper">
            <div class="page-content">
                <div class="row">
                    <section>
                        @RenderBody()
                    </section>
                </div>
            </div>
        </div>
    </div>
    @*模板页内容部分末*@
    @*模板页页脚部分始*@
    <div class="page-footer">
        <div class="page-footer-inner">
            2016&copy; 王凯-毕业设计（SAAS-OA)
        </div>
        <div class="scroll-to-top">
            <i class="icon-arrow-up"></i>
        </div>
    </div>
    @*模板页页脚部分末*@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Content/js/core")
    @Scripts.Render("~/Content/js/global")
    @Scripts.Render("~/Content/js/plugins/model")
    @Scripts.Render("~/Content/js/layout")
    @Scripts.Render("~/Content/js/plugins/datatables")
    @Scripts.Render("~/Content/js/plugins/mvcpager")
    @RenderSection("scripts", required: false)
</body>
</html>