Saas.Office.Auto.Web/Areas/Admin/Controllers/EnterpriseManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Saas.Office.Auto.Model;
using Saas.Office.Auto.GlobalUtilities.ValidateCode;
using Saas.Office.Auto.IService;
using Saas.Office.Auto.Service;
using Saas.Office.Auto.DataAccess;
using Webdiyer.WebControls.Mvc;
using Saas.Office.Auto.Web.Controllers;
using Saas.Office.Auto.Web.App_Start.Webstack;

namespace Saas.Office.Auto.Web.Areas.Admin.Controllers
{
    public class EnterpriseManagementController : BaseController
    {
        private readonly ISysEnterpriseService _sysEnterpriseService;
        public EnterpriseManagementController(ISysEnterpriseService sysEnterpriseService)
        {
            this._sysEnterpriseService = sysEnterpriseService;
        }
        //平台企业——企业管理
        // GET: Admin/EnterpriseManagement
        #region Index
        public ActionResult Index(int pageNum = 1)
        {
            EnterpriseManagementSearchModel model = new EnterpriseManagementSearchModel();
            PagedList<EnterpriseManagementViewModel> pagelist = _sysEnterpriseService.SearchHandle(model, pageNum);
            if (Request.IsAjaxRequest())
                return PartialView("_PartialIndex", pagelist);
            return View(pagelist);
        }
        [HttpPost]
        [AntiSqlInject]
        public ActionResult Index(EnterpriseManagementSearchModel model, int pageNum = 1)
        {
            PagedList<EnterpriseManagementViewModel> pagelist = _sysEnterpriseService.SearchHandle(model, pageNum);
            if (Request.IsAjaxRequest())
                return PartialView("_PartialIndex", pagelist);
            return View(pagelist);
        }
        #endregion
        #region Create
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [AntiSqlInject]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EnterpriseManagementViewModel model)
        {
            if (ModelState.IsValid)
            {
                bool result = _sysEnterpriseService.Add(model);
                if (result)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }
            }
            return View();
        }
        #endregion
        #region Delete
        [HttpPost]
        public ActionResult Delete(int id)
        {
            return View();
        }
        #endregion
        #region Edit
        public ActionResult Edit(int id)
        {
            EnterpriseManagementViewModel model = _sysEnterpriseService.GetEnterpriseManagementViewModel(id);
            if (model == null)
            {
                return View("Index");
            }
            return View(model);
        }
        [HttpPost]
        [AntiSqlInject]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EnterpriseManagementViewModel model)
        {
            if (ModelState.IsValid)
            {
                bool result = _sysEnterpriseService.Update(model);
                if (result)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }
            }
            return View(model);
        }
        #endregion
        #region Detail
        public ActionResult Detail(int id)
        {
            EnterpriseManagementViewModel model = _sysEnterpriseService.GetEnterpriseManagementViewModel(id);
            if (model == null)
            {
                return View("Index");
            }
            return View(model);
        }
        #endregion
    }
}

Saas.Office.Auto.Web/Areas/Admin/Views/EnterpriseManagement/Create.cshtml
@model Saas.Office.Auto.Model.EnterpriseManagementViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="/Admin/Home/Index">平台企业</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="~/Admin/EnterpriseManagement/Index">企业管理</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span>添加</span>
        </li>
    </ul>
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light">
                <div class="portlet-body">
                    <div class="table-toolbar">
                        <div class="form-horizontal">
                            <h4>添加</h4>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(model => model.EnterpriseName, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.EnterpriseName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.EnterpriseName, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.MaxUser, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.MaxUser, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.MaxUser, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.EnterpriseCode, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.EnterpriseCode, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.EnterpriseCode, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Validity, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Validity, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Validity, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.IsEnabled, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.IsEnabled, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.IsEnabled, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="添加" class="btn btn-default" />
                                    <a href="/Admin/EnterpriseManagement/Index">
                                        <input type="button" value="返回" class="btn btn-default" />
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

Saas.Office.Auto.Web/Areas/Admin/Views/EnterpriseManagement/Detail.cshtml
@model Saas.Office.Auto.Model.EnterpriseManagementViewModel

@{
    ViewBag.Title = "Detail";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="/Admin/Home/Index">平台企业</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="~/Admin/EnterpriseManagement/Index">企业管理</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span>详情</span>
        </li>
    </ul>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="portlet light">
            <div class="portlet-body">
                <div class="table-toolbar">
                    <div>
                        <h4>详情</h4>
                        <hr />
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.EnterpriseName)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.EnterpriseName)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.MaxUser)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.MaxUser)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.EnterpriseCode)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.EnterpriseCode)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Validity)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Validity)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.IsEnabled)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.IsEnabled)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.CreatedDate)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.CreatedDate)
                            </dd>

                        </dl>
                    </div>
                    <p>
                        <a href="/Admin/EnterpriseManagement/Edit/@Model.Id">
                            <input type="button" value="编辑" class="btn btn-default" />
                        </a>
                        <a href="/Admin/EnterpriseManagement/Index">
                            <input type="button" value="返回" class="btn btn-default" />
                        </a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

Saas.Office.Auto.Web/Areas/Admin/Views/EnterpriseManagement/Edit.cshtml
@model Saas.Office.Auto.Model.EnterpriseManagementViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="/Admin/Home/Index">平台企业</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="~/Admin/EnterpriseManagement/Index">企业管理</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span>编辑</span>
        </li>
    </ul>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light">
                <div class="portlet-body">
                    <div class="table-toolbar">
                        <div class="form-horizontal">
                            <h4>EnterpriseManagementViewModel</h4>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.Id)

                            <div class="form-group">
                                @Html.LabelFor(model => model.EnterpriseName, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.EnterpriseName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.EnterpriseName, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.MaxUser, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.MaxUser, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.MaxUser, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.EnterpriseCode, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.EnterpriseCode, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.EnterpriseCode, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Validity, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Validity, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Validity, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.IsEnabled, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.IsEnabled, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.IsEnabled, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="修改" class="btn btn-default" />
                                    <a href="/Admin/EnterpriseManagement/Index">
                                        <input type="button" value="返回" class="btn btn-default" />
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    
}

Saas.Office.Auto.Web/Areas/Admin/Views/EnterpriseManagement/Index.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<Saas.Office.Auto.Model.EnterpriseManagementViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="icon-home"></i>
            <a href="/Admin/Home/Index">平台企业</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span>企业管理</span>
        </li>
    </ul>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="portlet light">
            <div class="portlet-body">
                <div class="table-toolbar">
                    @*按钮区开始*@
                    <div class="col-md-5 col-sm-5">
                        <div class="">
                            <button class="btn btn-default" control-name="importexcel">
                                导出数据
                            </button>
                            <a id="addBtn" class="btn sbold green" href="/Admin/EnterpriseManagement/ShowPop" data-ajax-update="#modeldialog" data-ajax-success="AddAccountHandler"
                               data-ajax-mode="replace" data-ajax-method="Post" data-ajax="true">
                                添加
                                <i class="fa fa-plus"></i>
                            </a>
                            @*@Ajax.ActionLink("添加", "ShowPop", "EnterpriseManagement", new AjaxOptions() { HttpMethod = "Post", UpdateTargetId = "modeldialog", OnSuccess = "AddAccountHandler" }
                                , new { @class = "btn sbold green", area = "Admin" })*@
                            <a id="delBtn" class="btn sbold red">
                                删除
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    @*按钮区结束*@
                    @*查询区开始*@
                    <div class="col-md-7">
                        <div class="pull-right">
                            @using (Ajax.BeginForm("Index", "EnterpriseManagement", new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "Update" }, new { id = "Search", area = "Admin" }))
                            {
                                <label>
                                    企业名称：
                                    @Html.TextBox("EnterpriseName", "", new { @class = "form-control input-sm input-small input-inline", placeholder = "企业名称" })
                                </label>
                                <button type="submit" class="btn sbold green">查询</button>
                            }
                        </div>
                    </div>
                    @*查询区结束*@
                </div>
                <div id="Update">
                    @* 分布试图 *@
                    @Html.Partial("_PartialIndex", Model)
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade draggable-modal" id="draggable" tabindex="-1" role="dialog" aria-hidden="true">
    <div id="modeldialog" class="modal-dialog" style="background-color:#fff">
        <div class="modal-content">
        </div>
    </div>
</div>
@section scripts{
    <script type="text/javascript">

        function CheckAllHandler() {
            var table = $("#MyTable");
            var set = $("#btnCheckAll").attr("data-set");
            var checked = $("#btnCheckAll").is(":checked");
            $(set).each(function () {
                if (checked) {
                    $(this).prop("checked", true);
                    $(this).parents('tr').addClass("active");
                } else {
                    $(this).prop("checked", false);
                    $(this).parents('tr').removeClass("active");
                }
            });
        }
        function AddAccountHandler() {
            //成功后弹出模态框
            //$('#draggable').modal({
            //    keyboard: true
            //});
            $('#draggable').modal('show')
        }
    </script>
}

Saas.Office.Auto.Web/Areas/Admin/Views/EnterpriseManagement/_PartialIndex.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<Saas.Office.Auto.Model.EnterpriseManagementViewModel>
<table class="table  table-striped table-bordered table-hover table-checkable order-column" id="MyTable">
    <thead>
        <tr>
            <th>
                <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                    <input id="btnCheckAll" type="checkbox" class="group-checkable" data-set="#MyTable .checkboxes" onchange="CheckAllHandler()" />
                    <span></span>
                </label>
            </th>
            <th> @Html.DisplayNameFor(m => m.EnterpriseName)</th>
            <th> @Html.DisplayNameFor(m => m.EnterpriseCode)</th>
            <th> @Html.DisplayNameFor(m => m.MaxUser)</th>
            <th> @Html.DisplayNameFor(m => m.Validity)</th>
            <th>@Html.DisplayNameFor(m => m.CreatedDate)</th>
            <th> 操作 </th>
        </tr>
    </thead>
    <tbody id="tableBody">
        @if (Model != null && Model.Count() > 0)  //当数据不为空并且count>0时才能进行foreach循环
        {
            foreach (var item in Model)
            {
                <tr class="odd gradeX">
                    <td id="checkid">
                        <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                            <input type="checkbox" class="checkboxes" name="checkbox" id="@item.Id" autocomplete="off" />
                            <span></span>
                        </label>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EnterpriseName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EnterpriseCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MaxUser)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Validity)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedDate)
                    </td>
                    <td>
                        @Html.Hidden("Id", item.Id)
                        <a href="/Admin/EnterpriseManagement/Detail/@item.Id" class="btn default">
                            详情
                        </a>
                        <a href="/Admin/EnterpriseManagement/Edit/@item.Id" class="btn default">
                            编辑
                        </a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<div class="row">
    <div class="col-md-4 col-sm-4">
        <div class="dataTables_info andon-padding-top">
            共 @Model.TotalPageCount 页 @Model.TotalItemCount 条记录，当前为第 @Model.CurrentPageIndex 页
            <input id="currentPageIndexhid" type="hidden" value="@Model.CurrentPageIndex">
        </div>
    </div>
    <div class="andon-pagination col-md-8 col-sm-8">
        @Ajax.Pager(Model, new PagerOptions
   {
       //NumericPagerItemCount = Saas.Office.Auto.GlobalUtilities.Cookie.ConfigManager.Current.Settings.PagerBarShowNum,      //控制分页条显示页号
       NumericPagerItemCount = 5,
       PageIndexBoxId = "pageBox",    //选择要跳转select的id
       PageIndexParameterName = "pageNum", //与控制器中的pageNum绑定 当前第几页
       CssClass = "pagination",
       CurrentPagerItemTemplate = "<li class=\"active\"><a href=\"#\">{0}</a></li>",
       DisabledPagerItemTemplate = "<li class=\"disabled\"><a>{0}</a></li>",
       PagerItemTemplate = "<li>{0}</li>",
       Id = "bootstrappager2",
       AutoHide = false,
       PrevPageText = "上一页",
       NextPageText = "下一页",
       FirstPageText = "首页",
       LastPageText = "末页",
       HtmlAttributes = new Dictionary<string, object> { },
   }, new MvcAjaxOptions { UpdateTargetId = "Update", HttpMethod = "Post", DataFormId = "Search" })  @*与主页面Index中的查询div的id searchForm绑定*@
</div>

</div>