Saas.Office.Auto.Web/Areas/Admin/Controllers/DepartmentManagementController.cs
using Saas.Office.Auto.IService;
using Saas.Office.Auto.Model;
using Saas.Office.Auto.Service;
using Saas.Office.Auto.Web.App_Start.Webstack;
using Saas.Office.Auto.Web.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Webdiyer.WebControls.Mvc;

namespace Saas.Office.Auto.Web.Areas.Admin.Controllers
{
    public class DepartmentManagementController : BaseController
    {
        private readonly ISysDepartmentService _sysDepartmentService;
        public DepartmentManagementController(
            ISysDepartmentService sysDepartmentService)
        {
            this._sysDepartmentService = sysDepartmentService;
        }
        //平台企业——部门管理
        // GET: Admin/DepartmentManagement
        #region Index
        public ActionResult Index(int pageNum = 1)
        {
            DepartmentManagementSearchModel model = new DepartmentManagementSearchModel();
            PagedList<DepartmentManagementViewModel> pagelist = _sysDepartmentService.SearchHandle(model, pageNum);
            if (Request.IsAjaxRequest())
                return PartialView("_PartialIndex", pagelist);
            return View(pagelist);
        }
        [HttpPost]
        [AntiSqlInject]
        public ActionResult Index(DepartmentManagementSearchModel model, int pageNum = 1)
        {
            PagedList<DepartmentManagementViewModel> pagelist = _sysDepartmentService.SearchHandle(model, pageNum);
            if (Request.IsAjaxRequest())
                return PartialView("_PartialIndex", pagelist);
            return View(pagelist);
        }
        #endregion
        #region Detail
        public ActionResult Detail(int id)
        {
            DepartmentManagementViewModel model = _sysDepartmentService.GetDepartmentManagementViewModel(id);
            if (model == null)
            {
                return View("Index");
            }
            return View(model);
        }
        #endregion
    }
}

Saas.Office.Auto.Web/Areas/Admin/Views/DepartmentManagement/Index.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<Saas.Office.Auto.Model.DepartmentManagementViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="icon-home"></i>
            <a href="/Admin/Home/Index">平台企业</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span>部门管理</span>
        </li>
    </ul>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="portlet light">
            <div class="portlet-body">
                <div class="table-toolbar">
                    @*按钮区开始*@
                    <div class="col-md-5 col-sm-5">
                        <div class="">
                            <button class="btn btn-default" control-name="importexcel">
                                导出数据
                            </button>
                        </div>
                    </div>
                    @*按钮区结束*@
                    @*查询区开始*@
                    <div class="col-md-7">
                        <div class="pull-right">
                            @using (Ajax.BeginForm("Index", "DepartmentManagement", new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "Update" }, new { id = "Search", area = "Admin" }))
                            {
                                <label>
                                    企业名称：
                                    @Html.TextBox("DepartmentName", "", new { @class = "form-control input-sm input-small input-inline", placeholder = "部门名称" })
                                </label>
                                <button type="submit" class="btn sbold green">查询</button>
                            }
                        </div>
                    </div>
                    @*查询区结束*@
                </div>
                <div id="Update">
                    @* 分布试图 *@
                    @Html.Partial("_PartialIndex", Model)
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script type="text/javascript">

        function CheckAllHandler() {
            var table = $("#MyTable");
            var set = $("#btnCheckAll").attr("data-set");
            var checked = $("#btnCheckAll").is(":checked");
            $(set).each(function () {
                if (checked) {
                    $(this).prop("checked", true);
                    $(this).parents('tr').addClass("active");
                } else {
                    $(this).prop("checked", false);
                    $(this).parents('tr').removeClass("active");
                }
            });
        }
        function AddAccountHandler() {
            //成功后弹出模态框
            //$('#draggable').modal({
            //    keyboard: true
            //});
            $('#draggable').modal('show')
        }
    </script>
}

Saas.Office.Auto.Web/Areas/Admin/Views/DepartmentManagement/_PartialIndex.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<Saas.Office.Auto.Model.DepartmentManagementViewModel>
<table class="table  table-striped table-bordered table-hover table-checkable order-column" id="MyTable">
    <thead>
        <tr>
            <th>
                <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                    <input id="btnCheckAll" type="checkbox" class="group-checkable" data-set="#MyTable .checkboxes" onchange="CheckAllHandler()" />
                    <span></span>
                </label>
            </th>
            <th> @Html.DisplayNameFor(m => m.DepartmentName)</th>
            <th> @Html.DisplayNameFor(m => m.DepartmentCode)</th>
            <th> @Html.DisplayNameFor(m => m.CreatedDate)</th>
            <th> 操作 </th>
        </tr>
    </thead>
    <tbody id="tableBody">
        @if (Model != null && Model.Count() > 0)  //当数据不为空并且count>0时才能进行foreach循环
        {
            foreach (var item in Model)
            {
                <tr class="odd gradeX">
                    <td id="checkid">
                        <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                            <input type="checkbox" class="checkboxes" name="checkbox" id="@item.Id" autocomplete="off" />
                            <span></span>
                        </label>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DepartmentName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DepartmentCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedDate)
                    </td>
                    <td>
                        @Html.Hidden("Id", item.Id)
                        <a href="/Admin/DepartmentManagement/Detail/@item.Id" class="btn default">
                            详情
                        </a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<div class="row">
    <div class="col-md-4 col-sm-4">
        <div class="dataTables_info andon-padding-top">
            共 @Model.TotalPageCount 页 @Model.TotalItemCount 条记录，当前为第 @Model.CurrentPageIndex 页
            <input id="currentPageIndexhid" type="hidden" value="@Model.CurrentPageIndex">
        </div>
    </div>
    <div class="andon-pagination col-md-8 col-sm-8">
        @Ajax.Pager(Model, new PagerOptions
   {
       //NumericPagerItemCount = Saas.Office.Auto.GlobalUtilities.Cookie.ConfigManager.Current.Settings.PagerBarShowNum,      //控制分页条显示页号
       NumericPagerItemCount = 10,
       PageIndexBoxId = "pageBox",    //选择要跳转select的id
       PageIndexParameterName = "pageNum", //与控制器中的pageNum绑定 当前第几页
       CssClass = "pagination",
       CurrentPagerItemTemplate = "<li class=\"active\"><a href=\"#\">{0}</a></li>",
       DisabledPagerItemTemplate = "<li class=\"disabled\"><a>{0}</a></li>",
       PagerItemTemplate = "<li>{0}</li>",
       Id = "bootstrappager2",
       AutoHide = false,
       PrevPageText = "上一页",
       NextPageText = "下一页",
       FirstPageText = "首页",
       LastPageText = "末页",
       HtmlAttributes = new Dictionary<string, object> { },
   }, new MvcAjaxOptions { UpdateTargetId = "Update", HttpMethod = "Post", DataFormId = "Search" })  @*与主页面Index中的查询div的id searchForm绑定*@
</div>

</div>